use TypedDict for return type of legacy detect()
Ousret/charset_normalizer pull request #469
Opened 2024-05-14 11:37 UTC by pinterior

### Problem to solve

when I write something like:
```python3
x = charset_normalizer.detect(...)["encoding"]
```

`x` is inferred as `str | float | None` instead of actual `str | None`.

### Change

use custom `TypedDict` type as the return type of `detect` method if Python version >= 3.8.
(`TypeDict` is not available in Python 3.7)

2024-05-15 05:22 UTC, Ousret requested changes
OK. The idea behind this is useful.
There's a stunt we can put in place to avoid the Python 3.7 blocker. Look at my draft suggestion for more.

I suggest otherwise to use the main API wherever you can.

2024-05-15 05:22 UTC, Ousret commented on charset_normalizer/legacy.py
> +    from typing import TypedDict
```suggestion
if TYPE_CHECKING:
    from typing_extensions import TypedDict
```

2024-05-15 05:22 UTC, Ousret commented on charset_normalizer/legacy.py
>  from typing import Any, Dict, Optional, Union
```suggestion
from typing import Any, Dict, Optional, Union, TYPE_CHECKING
```

2024-05-15 05:22 UTC, Ousret commented on charset_normalizer/legacy.py
> +import sys
```suggestion
from __future__ import annotations
```

2024-05-15 05:22 UTC, Ousret commented on charset_normalizer/legacy.py
> +    ResultDict = Dict[str, Optional[Union[str, float]]]
```suggestion
```

2024-05-15 10:47 UTC, pinterior commented
> There's a stunt we can put in place to avoid the Python 3.7 blocker. Look at my draft suggestion for more.

that makes sense. committed.

2024-05-15 16:29 UTC, pinterior commented
CI action "MypyC Tests (3.7, macos-latest) (pull_request)" failing due to https://github.com/actions/runner-images/issues/9770
should I create separate PR to use 'macos-13' image for Python 3.7 instead of 'macos-latest'?

2024-05-18 03:55 UTC, Ousret commented
> should I create separate PR to use 'macos-13' image for Python 3.7 instead of 'macos-latest'?

no need, I will reorganize the whole thing anyway.

2024-05-18 03:56 UTC, Ousret approved these changes

2024-05-18 03:56 UTC, merged